// Edignite NGO Website Data

export const ngoInfo = {
  name: "Edignite",
  tagline: "HOPE FOR OTHERS",
  mission:
    "Ed-Ignite - as the name suggests, 'igniting' a spark of 'education' amongst the underprivileged kids - thus achieving Dr. APJ Adbul Kalam's dream of an educated India",
  vision:
    "A world where every child, regardless of their background, has access to quality education and opportunities to realize their full potential, creating an educated and empowered communities and world.",
  email: "edignitengo@gmail.com",
  phone: "+91-7984844099",
  address: "Surat, Gujarat, India",
  founded: "2019",
  website: "http://edignitengo.org",
  instagram: "https://www.instagram.com/ed_ignite/",
  linkedin: "https://in.linkedin.com/company/edignite-ngo",
  facebook: "https://www.facebook.com/socialindiagroup.in/",
  volunteerForm: "https://bit.ly/Edignite_Joining_Form",
  kalamQuote:
    "Education is the most powerful weapon which you can use to change the world.",
};

export const programs = [
  {
    id: 1,
    title: "Mentorship and Education",
    description:
      "Providing free mentorship and assisting underprivileged kids in their education, making them self-dependent, empowered professionals of future.",
    color: "from-blue-500 to-cyan-500",
    stats: "500+ Children mentored",
  },
  {
    id: 2,
    title: "Creative Arts",
    description:
      "Encouraging young artists in the srtudents and making them participate in numerous art, music and dance events.",
    color: "from-pink-500 to-rose-500",
    stats: "5+ Competitions round the year",
  },
  {
    id: 3,
    title: "Online Mentorship",
    description:
      "Shaping the future of students by connecting them with industry experts through online mentorship programme",
    color: "from-orange-500 to-yellow-500",
    stats: "60+ sessions conducted",
  },
  {
    id: 4,
    title: "Events and Celebrations",
    description:
      "Imparting the values of curiosity, helpfulness, determination, etc. through numerous celebrations, events and festivals",
    color: "from-teal-500 to-blue-500",
    stats: "20+ events celebrated round the year",
  },
  {
    id: 5,
    title: "School Admissions",
    description:
      "Enrolling underprivileged and unschooled kids to formal education, and thus helping them build a secured future",
    color: "from-teal-500 to-blue-500",
    stats: "10+ kids enrolled till now.",
  },
  {
    id: 6,
    title: "Distribution Drives",
    description:
      "Helping kids with their daily needs through distribution drives of various stationery items, clothes, footwear, water bottles, etc",
    color: "from-teal-500 to-blue-500",
    stats: "30+ distribution drives conducted till now.",
  },
];

export const impactStats = [
  {
    id: 1,
    number: "500+",
    label: "Children Impacted",
    icon: "👶",
    color: "text-pink-500",
  },
  {
    id: 2,
    number: "1000+",
    label: "Followers & Supporters",
    icon: "❤️",
    color: "text-red-500",
  },
  {
    id: 3,
    number: "60+",
    label: "Team Members",
    icon: "👥",
    color: "text-blue-500",
  },
  {
    id: 4,
    number: "5+",
    label: "Years of Service",
    icon: "🎉",
    color: "text-yellow-500",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Vishal Pandya",
    role: "Advocate",
    content:
      "The volunteers and trustees at Edignite are students who are balancing their Education and Education of underprivileged kids. They source the deprived kids, make them realise the value of Education, and educate them. Apart from education, the organization also focuses on activities which lead to overall development of kids. Having witnessed the activities of Edignite volunteers, I really appreciate the efforts they put in the education of kids. I am heartly touched by their service and like the way they fulfill their duty to the society.",
    avatar: "👨",
  },
  {
    id: 2,
    name: "Falguni Modi",
    role: "Social Worker",
    content:
      "I am a Social Worker, and have taught several underprivileged kids at slums for years. Thus, I feel very happy to see Edignite Volunteers teach the little kids. The thing I like about Edignite volunteers is that they are students who are hustling in their lives too. Still the take out some hours from their valuable time and teach these kids. As it is rightly said, charity of knowledge is the greatest charity, I salute the Edignite team for their charity of knowledge.",
    avatar: "👨",
  },
];

export const events = [
  {
    id: 1,
    title: "Foundation Day Celebration",
    date: "2025-02-11",
    location: "Surat, Gujarat",
    description:
      "Annual celebration of Edignite's foundation day with volunteer appreciation, group outings, and planning sessions for future initiatives.",
  },
  {
    id: 2,
    title: "NCC SVNIT Chapter Exhibition Visit",
    date: "2024-04-18",
    location: "SVNIT, Surat",
    description:
      "Children visited the NCC SVNIT Chapter Exhibition, witnessing innovation, discipline, and leadership up close. A day full of learning and new experiences.",
  },
  {
    id: 3,
    title: "Winter Gift Distribution",
    date: "2024-12-25",
    location: "Surat",
    description:
      "Christmas celebration with gift distribution to children, spreading joy and happiness during the festive season.",
  },
  {
    id: 4,
    title: "Volunteer Recruitment Drive",
    date: "2024-11-20",
    location: "Online & Surat",
    description:
      "Recruitment drive for passionate volunteers to join our mission of providing education to underprivileged children. Registration open for all interested individuals.",
  },
];

export const galleryCategories = [
  { id: "all", name: "All Photos", icon: "📸" },
  { id: "education", name: "Education", icon: "📚" },
  { id: "events", name: "Events & Celebrations", icon: "🎉" },
  { id: "achievements", name: "Student Achievements", icon: "🏆" },
  { id: "distribution", name: "Distribution Drives", icon: "🤝" },
  { id: "meetups", name: "Volunteer Meetups", icon: "👥" },
];

export const galleryImages = [
  {
    id: 1,
    category: "education",
    title: "Teaching at Kargil Chowk",
    description: "Children engaged in interactive learning activities",
    image: "/gallery/education-1.png",
    date: "2025",
  },
  {
    id: 2,
    category: "education",
    title: "Teaching at Karunasagar Garden",
    description: "Children engaged in interactive learning activities",
    image: "/gallery/education-2.png",
    date: "2024",
  },
  {
    id: 3,
    category: "education",
    title: "Teaching at Floral Garden Temple",
    description: "Children engaged in interactive learning activities",
    image: "/gallery/education-3.png",
    date: "2023",
  },
  {
    id: 4,
    category: "education",
    title: "Teaching near Umra Gam BRTS",
    description: "Children engaged in interactive learning activities",
    image: "/gallery/education-4.png",
    date: "2024",
  },
  {
    id: 5,
    category: "education",
    title: "Teaching at Umra Gam",
    description: "Children engaged in interactive learning activities",
    image: "/gallery/education-5.png",
    date: "2020",
  },
  {
    id: 6,
    category: "education",
    title: "Teaching near Nilam Society",
    description: "Children engaged in interactive learning activities",
    image: "/gallery/education-6.png",
    date: "2023",
  },
  {
    id: 7,
    category: "education",
    title: "Teaching at Gurgaon Center",
    description: "Children engaged in interactive learning activities",
    image: "/gallery/education-7.png",
    date: "2024",
  },
  {
    id: 8,
    category: "education",
    title: "Teaching at Anaganwadi (Kargil Chowk)",
    description: "Children engaged in interactive learning activities",
    image: "/gallery/education-8.png",
    date: "2025",
  },
  {
    id: 9,
    category: "education",
    title: "Teaching at Adajan Gam",
    description: "Children engaged in interactive learning activities",
    image: "/gallery/education-9.png",
    date: "2025",
  },
  {
    id: 10,
    category: "events",
    title: "Student Day Celebration",
    description: "Student Day Celebration on the eve of Dr. APJ Abdul Kalam's birthday",
    image: "/gallery/events-1.png",
    date: "2024",
  },
  {
    id: 11,
    category: "events",
    title: "Student Day Celebration",
    description: "Student Day Celebration on the eve of Dr. APJ Abdul Kalam's birthday",
    image: "/gallery/events-2.png",
    date: "2024",
  },
  {
    id: 12,
    category: "events",
    title: "Children's Day Celebration",
    description: "Celebrating children's day with all kids in Surat",
    image: "/gallery/events-3.png",
    date: "2025",
  },
  {
    id: 13,
    category: "events",
    title: "Republic Day Exhibition",
    description: "Children explaining Republic Day's exhibits to Professor",
    image: "/gallery/events-4.png",
    date: "2024",
  },
  {
    id: 14,
    category: "events",
    title: "Janmastami Celebration",
    description: "Children clebrating Janmastami at SVNIT Surat",
    image: "/gallery/events-5.png",
    date: "2024",
  },
  {
    id: 15,
    category: "events",
    title: "NCC Camp Visit",
    description: "Children's visit to NCC Camp at SVNIT Surat",
    image: "/gallery/events-6.png",
    date: "2024",
  },
  {
    id: 16,
    category: "events",
    title: "NCC Camp Visit",
    description: "Children engaged in NCC Camp activities",
    image: "/gallery/events-7.png",
    date: "2024",
  },
  {
    id: 17,
    category: "events",
    title: "Makarsankranti Celebration",
    description: "Children celebrating Makarsankranti with balloons and kites at Floral Garden",
    image: "/gallery/events-8.png",
    date: "2024",
  },
  {
    id: 18,
    category: "events",
    title: "Self Defence Camp",
    description: "Female Students participating in Self Defence Camp organized in Surat",
    image: "/gallery/events-9.png",
    date: "2024",
  },
  {
    id: 19,
    category: "events",
    title: "Independence Day Celebration",
    description: "Children celebrating Unity in Diversity on Independence Day",
    image: "/gallery/events-10.png",
    date: "2024",
  },
  {
    id: 20,
    category: "events",
    title: "Book Fair Visit",
    description: "Children selecting books at Kitablovers' book fair in Surat",
    image: "/gallery/events-11.png",
    date: "2024",
  },
  {
    id: 21,
    category: "events",
    title: "Birthday Celebrations",
    description: "Visit of children to restaurant during birthdays and celebrations",
    image: "/gallery/events-12.png",
    date: "2024",
  },
  {
    id: 22,
    category: "events",
    title: "Parent Counselling",
    description: "Parent Counselling by volunteers at Edignite",
    image: "/gallery/events-13.png",
    date: "2024",
  },
  {
    id: 23,
    category: "achievements",
    title: "Anshu's achievement in drawing and essay writing competition",
    description: "Anshu's 3rd rank and overall 1st rank in drawing and essay competition respectively",
    image: "/gallery/ach-1.png",
    date: "2024",
  },
  {
    id: 24,
    category: "achievements",
    title: "District level achievement of kids in a Sports Competition",
    description: "The team that included two of Edignite student's won a district level frisbee competition",
    image: "/gallery/ach-2.png",
    date: "2024",
  },
  {
    id: 25,
    category: "distribution",
    title: "Food Distribution drives",
    description: "One of regular food distribution drives conducted in Surat",
    image: "/gallery/dist-1.png",
    date: "2024",
  },
  {
    id: 26,
    category: "distribution",
    title: "Book Distribution",
    description: "One of several book distribution drives conducted in Surat",
    image: "/gallery/dist-2.png",
    date: "2024",
  },
  {
    id: 27,
    category: "distribution",
    title: "Book Distribution",
    description: "One of several book distribution drives conducted in Rajkot",
    image: "/gallery/dist-3.png",
    date: "2024",
  },
  {
    id: 28,
    category: "distribution",
    title: "Sweater Distribution",
    description: "Distribution of sweater and winter wear during December",
    image: "/gallery/dist-4.png",
    date: "2024",
  },
  {
    id: 29,
    category: "distribution",
    title: "Mask & Sanitizer Distribution",
    description: "Distribution of masks and sanitizers during COVID-19",
    image: "/gallery/dist-5.png",
    date: "2020",
  },
  {
    id: 30,
    category: "distribution",
    title: "Cloth Distribution",
    description: "Photos from cloth distribution drive",
    image: "/gallery/dist-6.png",
    date: "2024",
  },
  {
    id: 31,
    category: "distribution",
    title: "Donation Plate",
    description: "Donation Plate kept at a hostel canteen in SVNIT, where students can contribute a spoon/part of the meal from their plate to fill stomach of one child",
    image: "/gallery/dist-7.png",
    date: "2024",
  },
  {
    id: 32,
    category: "distribution",
    title: "Donation Plate",
    description: "One of the photos from regular visits for donation plate",
    image: "/gallery/dist-8.png",
    date: "2024",
  },
  {
    id: 33,
    category: "distribution",
    title: "Contribution Box",
    description: "Contibution box kept at one of the hostels, where people can donate items of daily use (eg: clothes) to kids - to be taken during our regular distribution drives",
    image: "/gallery/dist-9.png",
    date: "2024",
  },
  {
    id: 34,
    category: "meetups",
    title: "Volunteer Meet Up",
    description: "Volunteer meet up for recreation and to discuss progress and development of organization",
    image: "/gallery/meetup-1.png",
    date: "2024",
  },
];

export const blogPosts = [
  {
    id: 1,
    title: "Achieving Dr. Kalam's Dream: Educated India",
    excerpt:
      "Inspired by Dr. APJ Abdul Kalam's vision of an 'Educated India', Edignite is committed to providing quality education to every child, regardless of their background.",
    date: "2024-03-01",
    category: "Mission",
  },
  {
    id: 2,
    title: "Connecting Volunteers with Children Through WhatsApp",
    excerpt:
      "Our innovative WhatsApp groups connect passionate volunteers with children from slum areas, creating opportunities for skill sharing, birthday celebrations, and mentorship.",
    date: "2024-02-15",
    category: "Volunteering",
  },
  {
    id: 3,
    title: "Partnership with SVNIT: Opening Doors to Innovation",
    excerpt:
      "Our collaboration with SVNIT has enabled children to experience innovation, discipline, and leadership firsthand, inspiring them to dream bigger and achieve more.",
    date: "2024-04-18",
    category: "Partnerships",
  },
];

export const members = [
  {
    id: 2,
    name: "Aman",
    role: "Volunteer Coordinator",
    description: "Chemical Engineer (B.Tech.), NIT Surat",
    image: "/gallery/aman.jpg",
    email: "",
    linkedin: "https://www.linkedin.com/in/aman-vataliya/",
    instagram: "amanvataliya@gmail.com",
  },
  {
    id: 4,
    name: "Harsh",
    role: "Volunteer Coordinator",
    description: "National Physics Laboratory (AIR 82 - CSIR NET)",
    image: "/gallery/harsh.jpg",
    email: "harshmalaviya1212@gmail.com",
    linkedin: "https://www.linkedin.com/in/harsh-m-1660461b9/",
    instagram: "",
  },
  {
    id: 1,
    name: "Sachin",
    role: "Volunteer Coordinator",
    description: "Masters of Physics from NIT Surat",
    image: "/gallery/sachin.jpg",
    email: "sachinkumarogs@gmail.com",
    linkedin: "https://www.linkedin.com/in/sachin-kumar-09b008223/",
    instagram: "",
  },
  {
    id: 3,
    name: "Bhavya",
    role: "Volunteer Coordinator",
    description: "Masters of Physics from NIT Surat",
    image: "/gallery/bhavya.jpg",
    email: "bhavyapittaliya854@gmail.com",
    linkedin: "https://www.linkedin.com/in/bhavya-pittaliya-03b20a224/",
    instagram: "",
  },
  {
    id: 5,
    name: "Prince",
    role: "Founder",
    description: "Software Lead at OneAssist",
    image: "/gallery/prince.png",
    email: "princevermasrcc@gmail.com",
    linkedin: "https://www.linkedin.com/in/prince-verma-edignite/",
    instagram: "",
  },
  {
    id: 6,
    name: "Heer",
    role: "Secretary",
    description: "Software Developer, Google",
    image: "/gallery/heer.jpg",
    email: "mehtaheerh@gmail.com",
    linkedin: "https://www.linkedin.com/in/heer-mehta-edignite/",
    instagram: "",
  },
];
